### ISSUE TITLE
Cannot install Python dependencies

### ISSUE THREAD

**Issue by maurizi** [OpenTreeMap/otm-vagrant#37]
The bootstrap script fails when installing Python deps, it looks like the failure may be caused by `hiredis`

```

==> default: New python executable in env/bin/python
==> default: Installing setuptools, pip, wheel...
==> default:
==> default:   Complete output from command /usr/local/otm/env/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel:
==> default:   Traceback (most recent call last):
==> default:   File "<string>", line 1, in <module>
==> default:   File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-7.1.2-py2.py3-none-any.whl/pip/__init__.py", line 15, in <module>
==> default:   File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-7.1.2-py2.py3-none-any.whl/pip/vcs/mercurial.py", line 10, in <module>
==> default:   File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-7.1.2-py2.py3-none-any.whl/pip/download.py", line 45, in <module>
==> default:   File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-7.1.2-py2.py3-none-any.whl/pip/_vendor/cachecontrol/caches/__init__.py", line 15, in <module>
==> default:   File "/usr/local/otm/env/local/lib/python2.7/site-packages/redis/__init__.py", line 1, in <module>
==> default:     from redis.client import Redis, StrictRedis
==> default:   File "/usr/local/otm/env/local/lib/python2.7/site-packages/redis/client.py", line 10, in <module>
==> default:     from redis.connection import (ConnectionPool, UnixDomainSocketConnection,
==> default:   File "/usr/local/otm/env/local/lib/python2.7/site-packages/redis/connection.py", line 36, in <module>
==> default:     hiredis_version = StrictVersion(hiredis.__version__)
==> default: AttributeError: 'module' object has no attribute '__version__'
==> default: ----------------------------------------
==> default: ...Installing setuptools, pip, wheel...done.
==> default: Traceback (most recent call last):
==> default:   File "/usr/local/bin/virtualenv", line 9, in <module>
==> default:     load_entry_point('virtualenv==13.1.2', 'console_scripts', 'virtualenv')()
==> default:   File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 832, in main
==> default:     symlink=options.symlink)
==> default:   File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 1004, in create_environment
==> default:     install_wheel(to_install, py_executable, search_dirs)
==> default:   File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 969, in install_wheel
==> default:     'PIP_NO_INDEX': '1'
==> default:   File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 910, in call_subprocess
==> default:     % (cmd_desc, proc.returncode))
==> default: OSError: Command /usr/local/otm/env/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 1
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by jwalgran** [comment]
I just provisioned with the latest master (077d56f) and had no issues.
